### ISSUE TITLE
Removal request: acescans.xyz

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/tachiyomi-extensions#11021]
Requested by LIGHTNINGHAWK#4476 on Discord.

URL: http://acescans.xyz/

Pending verification of:

- [x] Proof of ownership (send to cesco#1141 via Discord DM)
- [ ] Site only hosts their own scanlated content and not stolen content
- [x] Site is not infested with user-hostile ads

**Comment by arkon** [comment]
For the record:

![](https://media.discordapp.net/attachments/364330965444853761/949692296079740938/unknown.png)

![](https://cdn.discordapp.com/attachments/364330965444853761/949695320827252736/unknown.png)

**Comment by FourTOne5** [comment]
Chapter behind Paywall: 
![image](https://user-images.githubusercontent.com/59261191/156890833-b658814d-8002-4656-8c94-26ecf9954485.png)

and there's also stolen content:
Chapter Ren’ai Shikou Seitokai
![image](https://user-images.githubusercontent.com/59261191/156890904-8714dc1b-9073-48f8-a27a-cabd930d1da2.png)

![image](https://user-images.githubusercontent.com/59261191/156890911-362d1f8a-a03d-4bb6-8680-ab8c3e4be407.png)

**Comment by arkon** [comment]
Closing but we can reconsider if content from other scanlators are either removed or verified to be partnered.
