### ISSUE TITLE
Xun scans: Site shutdown, can be removed 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi-extensions#14654]
### Source link

https://xunscans.xyz/

### Other details

Site shutdown due to DMCA, they are still active and upload to Mangadex
![Screenshot-1](https://user-images.githubusercontent.com/48650614/209418685-372a574c-439e-4f99-a9fe-44b141583bd8.png)
![Screenshot_1](https://user-images.githubusercontent.com/48650614/209418722-83d7cbcc-95b4-47d1-9c1a-a6678675c98c.png)

### Requirements

- [ ] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [ ] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [ ] Site is not infested with user-hostile features (e.g., invasive or malicious ads)
