### ISSUE TITLE
[Bug] Japscan: pages are empty, have ad on top of it or don't load at all

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi-extensions#6166]
## Device information
- Tachiyomi version: 0.10.9

## Source information
- Name: Japscan
- Extension version: 1.2.25

## Steps to reproduce
1. Read any manga/webtoon, happens randomly

### Expected behavior
Pages are loading fine and without any ad

### Actual behavior
Random pages can have one of the following problems (I'm not really sure, but 1 and 2 are probably the same issue):
- [ ] there is placeholder image instead of actual page (original issue #4759)
- [ ] pages are empty/blank/white (original issue #4792)
- [ ] there is ad on top of pages (original issue #4811)
- [ ] infinite load of chapter without any error, can't even get number of pages (original issue #6234)

## Other details
Clearing cache may help, but it will happen again on different pages.

### Please don't leave comments unless you can help fixing this.

**Comment by az4521** [comment]
lol gl fixing this

**Comment by BayLee4** [comment]
Hi, I wrote a patch that fix (at least) #6234. Additionally, it now intercepts Pages directly instead of relying on the Webview Screenshotter.

[fix_japscan.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6320122/fix_japscan.txt)

**Comment by RaniSargees** [comment]
yo pog someone actually fixed my garbage code

**Comment by az4521** [comment]
pog, someone fixed my garbage

**Comment by CarlosEsco** [comment]
@BayLee4 why not open a PR?

**Comment by BayLee4** [comment]
@az4521 loool, gg for writing it in the first place ^^
@CarlosEsco Okay no problem :)

**Comment by BayLee4** [comment]
opened #6566

**Comment by az4521** [comment]
so, there isnt a descrambler anymore after that PR
![Screenshot_20210415-171320_TachiyomiAZ](https://user-images.githubusercontent.com/18432684/114939281-36bcb680-9e0e-11eb-8f3b-92a0104e8d94.png)

**Comment by BayLee4** [comment]
Yes it's really annoying, I answered directly in the PR #6566 @az4521, do you want to continue the discussion here or in the PR ?

**Comment by BayLee4** [comment]
Do you have other titles known for having scrambled images ?

**Comment by BayLee4** [comment]
Ok, I got some new informations : 

Even with the webview screenshotter code back, it still doesn't work :/

It's because all canvas exists prior to the real loading of the image, so in the cleanup.js "checkExist" always return true even if the image is not loaded, thus taking an empty/blank screenshot.

I'm trying to find a way to detect the real loading of the images in the canvas.
Better : trying to extract the images from the canvas directly.

This is currently not possible because of CORS, when trying to extract the image like document.getElementsByTagName('CNV-VV')[WHATEVER_INDEX].all_canvas[THE_REAL_INDEX].toDataURL() it fails with "on 'HTMLCanvasElement': Tainted canvases may not be exported".

*WHATEVER_INDEX is 0 to Max pages.
*THE_REAL_INDEX is random (0 to 8, the real image is loaded in a random canvas, all others are empty)

On desktop, I launched Chrome with  --disable-web-security --disable-gpu in order to disable CORS, and I was able to extract the real image from the canvas 

So by making CORS happy in the android webview we will be able to extract all descrambled images

**Comment by GoToon69** [comment]
Hello ! I wanted to add the bug, but I'm late obviously 😅
Thanks for your work, it's amazing !!
I add the screenshot I made anyway.
![Screenshot_20210423-191841](https://user-images.githubusercontent.com/83087474/115907646-749e8800-a469-11eb-9d42-430cf95d904c.jpg)

**Comment by king07-0** [comment]
@BayLee4 I'm still using the previous version (1.2.25) and it unscramble correctly the chapter (expl boruto) and can download webtoon since today (last chapter of solo leveling). So I think you can rollback your PR and use the 1.2.25 for a new release.
