### ISSUE TITLE
Tsuki mangás problema

### ISSUE THREAD

**Issue by Messaih** [tachiyomiorg/tachiyomi-extensions#8130]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

O link da tsuki mangas foi alterado

**Comment by alessandrojean** [comment]
Duplicate of #8131

Tsuki situation better explained at the other issue.
